version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=kirrryu
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=shorty
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: